map_name: "sp_arena"
boost_locations:
  - [0,0,0]
lobby_name: "world"

arenas:
  - id: arena-1
    world: sp_arena
    teamCount: 2
    playersPerTeam: 3
  - id: arena-2
    world: sp_arena_2
    teamCount: 3
    playersPerTeam: 2

spartakiad:
  enabled: false
  minigame_name: "minigame"
  attempts: 5
  team_mode: false

uuid:
  use_libre_login: false

storage:
  debounce_millis: 500
  close_timeout_millis: 5000

teams:
  players_file: "teams.txt"