name: ${NAME}
version: ${VERSION}
api-version: ${MINECRAFT_VERSION}
main: ru.joutak.splatoon.SplatoonPlugin
description: 'splatoon'
authors: ['technosimp']
contributors: ['technosimp']
website: ${WEBSITE}
commands:
  splatoon:
    usage: "/splatoon <ник1> <ник2> ..."

depend: []
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib:${KOTLIN_VERSION}'