name: ${NAME}
version: ${VERSION}
api-version: ${MINECRAFT_VERSION}
main: ru.joutak.splatoon.SplatoonPlugin
description: 'splatoon'
authors: ['Saldaw', 'technosimp', ]
contributors: ['EnderDissa']
website: ${WEBSITE}
commands:
  splatoon:
    usage: "only with miniGAMES API"
  splatgun:
    permission: splatoon.admin
  splatbomb:
    permission: splatoon.admin
  bacillus:
    permission: splatoon.admin

permissions:
  splatoon.admin:
    default: op

depend: []
libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib:${KOTLIN_VERSION}'